services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # En producción, estas credenciales vivirán en un archivo .env seguro

  web:
    build: .
    # Mantenemos el contenedor vivo para poder ejecutar comandos interactivos
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "3000:3000" # Exponemos el puerto de Rails hacia nuestra máquina local
    depends_on:
      - db

volumes:
  # Volumen persistente para que los datos no se borren si apagamos el contenedor db
  postgres_data:
